In [ ]:
!pip install requests bs4 

Given a list with a maximum size of 10^6, for every element of that list, find the first largest element at the right side of that element.

In [6]:
sample_list = [100, 10, 25, 101]
stack = []
result = []

for itr in range(len(sample_list)-1, -1, -1):
    while len(stack) != 0 and stack[-1] <= sample_list[itr]:
        stack.pop(-1)

    stack.append(sample_list[itr])
    
    if len(stack) >= 2:
        result.append(stack[-2])
    else:
        result.append(None)
        
result.reverse()
print (result)

[101, 25, 101, None]


In [9]:
import requests
from bs4 import BeautifulSoup as bs

In [8]:
url = "http://www.hackerrank.com/dashboard"

In [10]:
r = requests.get(url)

In [11]:
soup = bs(r.text, "html.parser")

In [12]:
soup.find_all("h3", attrs={"class", "base-card-title"})

[<h3 class="base-card-title" title="Interview Preparation Kit">Interview Preparation Kit</h3>,
 <h3 class="base-card-title" title="Add your first skill">Add your first skill</h3>,
 <h3 class="base-card-title" title="Interview Preparation Kit">Interview Preparation Kit</h3>,
 <h3 class="base-card-title" title="Learn to code in 30 days">Learn to code in 30 days</h3>,
 <h3 class="base-card-title" title="10 Days of Statistics">10 Days of Statistics</h3>,
 <h3 class="base-card-title" title="10 Days of Javascript">10 Days of Javascript</h3>]

In [ ]:
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By

from bs4 import BeautifulSoup

url = "https://www.hackerrank.com/%s?hr_r=1"

usernames = [
    "skr",
    "aslangungor5571",
    "ceyaltay",
    "bugrahatipoglu",
    "burcukoc26",
    "salmanderen",
    "tari16",
    "ilaydaselinturk",
    "altunilayda8",
    "ilgazeyidogan",
    "rahimli_laman",
    "seyma_kozoglu",
    "tahafatih",
    "y_s_abazaoglu",
    "altuntasyunus50",
    "salmanselen",
    "buketbal",
    "craigkrais",
    "mehmetnur",
    "sevval_",
    "trkmnysmn06",
    "seyma_kozoglu",
    "iremnurdukan",
    "alperenk7",
    "dalkiranhacer7"
]

driver_path = "DRIVERPATH"
options = webdriver.ChromeOptions()
options.add_argument('headless')
browser = webdriver.Chrome(executable_path=driver_path)#, options=options)

for username in usernames:
    browser.get(url % username)

    try:
        wait = WebDriverWait(browser, 10)
        h3 = wait.until(EC.visibility_of_element_located((By.CSS_SELECTOR, ".history-list-item")))

        source = browser.page_source

        soup = BeautifulSoup(source, "html.parser")
        first_item = soup.find("div", attrs={"class", "history-list-item"})
        time = first_item.find("span").text
    except:
        continue

    print (username, time)

browser.close()

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data.txt", sep="\t")

In [3]:
df

Year  Month  Bought    Cost  Consumed
0   2018      1     500   30.51       450
1   2018      2    2000  139.63       900
2   2018      3    1500  110.97       950
3   2018      4    2000  145.19       900
4   2018      5    1000   73.98       870
5   2018      6    1000   73.98       800
6   2018      7    1000   73.98      1500
7   2018      8     250   18.47      1250
8   2018      9    1000   82.41      1500
9   2018     10    1000   91.67      1500
10  2018     11    1500  138.75      1400
11  2018     12    2500  256.25      1250
12  2019      1     500   50.88      1250
13  2019      2     500   50.88      1250

In [4]:
df.columns

Index(['Year', 'Month', 'Bought', 'Cost', 'Consumed'], dtype='object')

In [5]:
df.index

RangeIndex(start=0, stop=14, step=1)

In [6]:
df.dtypes

Year          int64
Month         int64
Bought        int64
Cost        float64
Consumed      int64
dtype: object

In [8]:
for bought, group in df.groupby("Bought"):
    print (bought)
    print(group)

250
   Year  Month  Bought   Cost  Consumed
7  2018      8     250  18.47      1250
500
    Year  Month  Bought   Cost  Consumed
0   2018      1     500  30.51       450
12  2019      1     500  50.88      1250
13  2019      2     500  50.88      1250
1000
   Year  Month  Bought   Cost  Consumed
4  2018      5    1000  73.98       870
5  2018      6    1000  73.98       800
6  2018      7    1000  73.98      1500
8  2018      9    1000  82.41      1500
9  2018     10    1000  91.67      1500
1500
    Year  Month  Bought    Cost  Consumed
2   2018      3    1500  110.97       950
10  2018     11    1500  138.75      1400
2000
   Year  Month  Bought    Cost  Consumed
1  2018      2    2000  139.63       900
3  2018      4    2000  145.19       900
2500
    Year  Month  Bought    Cost  Consumed
11  2018     12    2500  256.25      1250


In [9]:
df.describe()

Year      Month       Bought        Cost     Consumed
count    14.000000  14.000000    14.000000   14.000000    14.000000
mean   2018.142857   5.785714  1160.714286   95.539286  1126.428571
std       0.363137   3.786181   662.216143   60.815949   318.424176
min    2018.000000   1.000000   250.000000   18.470000   450.000000
25%    2018.000000   2.250000   625.000000   56.655000   900.000000
50%    2018.000000   5.500000  1000.000000   78.195000  1250.000000
75%    2018.000000   8.750000  1500.000000  131.805000  1362.500000
max    2019.000000  12.000000  2500.000000  256.250000  1500.000000

In [10]:
import numpy as np

In [13]:
l = [1,2,4,5]
k = [1,2,3,4]
k + l 

[1, 2, 3, 4, 1, 2, 4, 5]

In [14]:
l2 = np.array([1,2,4,5])
k2 = np.array([1,2,3,4])
k2 + l2

array([2, 4, 7, 9])

In [15]:
type(k)

list

In [16]:
type(k2)

numpy.ndarray

In [17]:
array2d = np.array([
    [1,2,3],
    [4,5,6]
])
array2d2 = np.array([
    [1,2],
    [4,5],
    [3,6]
])

In [18]:
np.matmul(array2d, array2d2)

array([[18, 30],
       [42, 69]])

In [19]:
array2d @ array2d2

array([[18, 30],
       [42, 69]])

In [20]:
array2d.shape

(2, 3)

In [21]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
sarray = np.array([
    [1,2,3],
    [4,5,3],
    [9,16,3],
])

In [23]:
np.linalg.inv(sarray)

array([[-0.61111111,  0.77777778, -0.16666667],
       [ 0.27777778, -0.44444444,  0.16666667],
       [ 0.35185185,  0.03703704, -0.05555556]])

In [24]:
np.linalg.matrix_power(sarray, 3)

array([[ 438,  660,  342],
       [ 699, 1083,  504],
       [1440, 2274,  990]])

In [25]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.linspace(0, 1000, 10)

array([   0.        ,  111.11111111,  222.22222222,  333.33333333,
        444.44444444,  555.55555556,  666.66666667,  777.77777778,
        888.88888889, 1000.        ])

In [27]:
np.random.randint(1,1000, (2,5))

array([[726, 582, 905, 955, 755],
       [224, 977, 510, 359, 957]])

In [29]:
sarray[2, 1]

16